[package]
name = "duk"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
duktape = { path = "../duktape" }
duktape-cjs = { path = "../duktape-cjs" }
log = "0.4"
env_logger = "0.5.13"

