[package]
name = "duktape"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
duktape_sys = { path = "../duktape_sys" }
error-chain = "0.12"
typemap = "0.3"
bitflags = "0.8"

[[example]]
name = "class"
path = "example/class.rs"