[package]
name = "duktape_es2015"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
duktape = { path = "../duktape", features = ["commonjs"] }

[features]
default = []
buildtime_bindgen = []