[package]
name = "duktape_sys"
version = "0.2.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"
build = "build.rs"

[features]
default = []
buildtime_bindgen = ["bindgen"]

[build-dependencies]
bindgen = { version = "^0.42", optional = true }
cc = "^1.0"



