[package]
name = "duktape-stdlib"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]
duktape = { path = "../duktape" }
duktape-cjs = { path = "../duktape-cjs" }